name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      id: Build
      run: dotnet build --configuration Release -p:DisableZipRelease=true
    - name: Echo Filename
      run: echo $BUILDTEXT
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./CITest/bin/Release/Output
